### ISSUE TITLE
Chrome extension to support Audio node

### ISSUE THREAD

**Issue by gsouquet** [bbc/VideoContext#107]
Hi,

Sorry to open an issue here, it's not super relevant to this repo.
Recently audio node support has been added to `VideoContext`, however the chrome extension does not support it just yet.

I opened a PR a while ago to support that: https://github.com/bbc/visualise-videocontext/pull/12
Once this PR is merged I will open another one in https://github.com/gsouquet/videocontext-devtools

I'm not sure who are the right people I need to talk to, to get that merged? Looks like the repo is quite inactive

Thank you, I'd appreciate your help with this

**Comment by PTaylour** [comment]
Oh fantastic! I'll release that now
