### ISSUE TITLE
Use requestAnimationFrame in the UpdatablesManager worker

### ISSUE THREAD

**Issue by gsouquet** [bbc/VideoContext#113]
In `src/utils.js` there is a class `UpdateablesManager` that is in charge or requesting animation frames and will iterate through every updatables item attached to the graph and paint the relevant ones on the destination.

Although there is one quirk, when a tab looses focus the user agent can decide to stop the animation frame loop. This creates a big problem as the library needs this loop to maintain the master clock.

This is why it's listening for the visibility change of the tab and it can spawn a worker that will maintain a less accurate clock using `setTimeout`.

With the release of `OffscreenCanvas` it is now possible to use `requestAnimationFrame` in a worker context.

We could definitely progressively enhance the experience and use `requestAnimationFrame` in a worker when available.

I will try to tackle that in the next few weeks

**Comment by PTaylour** [comment]
Great stuff

**Comment by gsouquet** [comment]
I was playing around with this. It seems that some browsers make some optimisation and will pause a RAF loop when the user switch tab to optimise the experience.

For some reason they don't block `setTimeout`... 

I guess it's safe to stick with the current solution that is in place
