### ISSUE TITLE
Slow scrubbing for videos

### ISSUE THREAD

**Issue by gsouquet** [bbc/VideoContext#114]
Hi,

We have spotted that video scrubbing can be quite slow using VideoContext. It can drop to 4/5 fps.
There are obviously a lot of factors that will come into play for that:
- Canvas drawingbuffer size
- Video dimensions
- Video encoding (whether it is optimised for fast decoding or not)
- Number of nodes that play in parallel 

To make sure that we would have a fair benchmark, @sacharified came up with a reduced test case that compares:
- Native video element scrubbing
- Scrubbing and painting on a `2dRenderingContext`
- Scrubbing and painting on a `WebGLRenderingContext` with the most simplistic shaders possible
- Scrubbing using VideoContext with a single node attached to the graph

You can try it for yourself: https://codepen.io/Sacharified/pen/dgderG?editors=0010

We are currently trying to investigate what the bottleneck is but it is slightly unclear as there are a lot of boilerplate code.
Is there some documentation somewhere that explain the WebGL program structure? That would really help to debug this issue further.
If you have any lead please let me know

**Comment by PTaylour** [comment]
That's a great codepen—and that is quite a difference between videocontext and the others

I'm afraid there isn't much in the way of implementation docs for videocontext itself.

**Comment by PTaylour** [comment]
Not sure as far as leads.

Looks like at one point it was waiting longer than necessary to update. But that is fixed now https://github.com/bbc/VideoContext/issues/59

**Comment by gsouquet** [comment]
Alright, I guess we'll do a bit of a reverse engineering session in the future and we'll try to document the way at the same time.

**Comment by gsouquet** [comment]
I forgot to update this issue.

I think this is more a video encoding problem rather than a VideoContext problem. I dug deep on this one and realised that the way that VC approached this was as optimised as it could be.

Changing the encoding parameters of our videos made a huge impact here.
