### ISSUE TITLE
Media Fragments

### ISSUE THREAD

**Issue by dr-offig** [bbc/VideoContext#149]
Video context doesn't seem to play well with Media Fragments. I am hoping to loop different subsections of a video. But, for example, in the code playground the following doesn't behave as expected

```javascript
var videoNode1 = vc.video("../../assets/introductions-rant.mp4#t=1,5", 0, 2, { loop: true });
var videoNode2 = vc.video("../../assets/introductions-rant.mp4#t=4,8", 0, 2, { loop: true });
var videoNode3 = vc.video("../../assets/introductions-rant.mp4#t=9,15", 0, 2, { loop: true });
```
Also tried
```javascript
var videoNode1 = vc.video("../../assets/introductions-rant.mp4#t=1,5", 1, 2, { loop: true });
var videoNode2 = vc.video("../../assets/introductions-rant.mp4#t=4,8", 4, 2, { loop: true });
var videoNode3 = vc.video("../../assets/introductions-rant.mp4#t=9,15", 9, 2, { loop: true });
```

**Comment by PTaylour** [comment]
Yep, videocontext takes that second argument (the `sourceOffset`) as the as the starting point and ignores any existing state of the video element.

It also appears that the end point (from which to loop from) is unaware of the fragment

So it would be a non breaking changes to ensure that 

- the `sourceOffset` is relative to the start of the fragment and not the start of the full video
- the duration is the fragment duration not the video duration


### Implementation
Do you know of the plans for media fragments? No real browser APIs  that I can see:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

![image](https://user-images.githubusercontent.com/3678476/55621516-a4509980-5795-11e9-9f21-59786978b441.png)

But would be pretty simple to parse ourselves from the src url. I guess that's the way forward.

Any thoughts?

**Comment by PTaylour** [comment]
adding this to my reading list: https://gingertech.net/tag/media-fragment-uri/

**Comment by dr-offig** [comment]
Thanks for looking at this Pete. Alternatively, can you suggest any other way to loop a section of a video using the library as it stands? I guess i'm trying to do something a bit different to what the library was designed for; i.e. interactive video stuff rather than compositional.

**Comment by PTaylour** [comment]
> interactive video stuff rather than compositional.
Thats quite a common use for it. I'd like to make videocontext more user friendly for interactive cases.

## How to loop video now

We've just released an API for custom nodes. So, for now, you could do a basic implementation in your own node.

https://codesandbox.io/embed/l7wz9qw3kq

If this works ^ for you I'll do the parsing properly and merge it into the actual `VideoNode`.

**Comment by dr-offig** [comment]
Thanks Pete, that's great!  Certainly covers my use-case. API for custom nodes is an awesome development.
