### ISSUE TITLE
Videos with Rotation Metadata

### ISSUE THREAD

**Issue by jrking4** [bbc/VideoContext#155]
When adding videos to the player, if the video came from a mobile device, they sometimes have rotation metadata stored in their file.  Browser html5 video elements seem to automatically orientate the videos. however they dont seem to be automatically orientated on the  canvas.

**Comment by PTaylour** [comment]
We're likely having the same issue as this https://github.com/bfred-it/video-canvas/issues/1

**Comment by PTaylour** [comment]
Could be tough as it looks like we don't have access to the rotation metadata in javascript

https://github.com/mrdoob/three.js/issues/13671#issuecomment-379705544

**Comment by PTaylour** [comment]
The first thread has a couple of suggestions of how to make do with that as a limitation, although it only covers a few use-cases

**Comment by PTaylour** [comment]
I'm not sure there is much we can do on this at the moment. I'm open for re-openning in the future.
