### ISSUE TITLE
Unidentified error message

### ISSUE THREAD

**Issue by pietrop** [bbc/VideoContext#160]
👋 
We have been using VideoContext in a BBC News Labs project [`bbc/digital-paper-edit-client`](https://github.com/bbc/digital-paper-edit-client) ( wrapped inside a React [`PreviewCanvas`](https://github.com/bbc/digital-paper-edit-client/tree/master/packages/client/src/Components/PaperEdits/PaperEdit/ProgramScript/PreviewCanvas) component - issue https://github.com/bbc/digital-paper-edit-client/issues/3 and PR https://github.com/bbc/digital-paper-edit-client/pull/11) 

When clicking on the [progress bar](https://github.com/bbc/digital-paper-edit-client/blob/master/packages/client/src/Components/PaperEdits/PaperEdit/ProgramScript/PreviewCanvas/VideoContextProgressBar.js) I get this error message in the console and couldn't quiet figure out what is causing it?

<img width="544" alt="Screen Shot 2019-05-20 at 22 27 11" src="https://user-images.githubusercontent.com/4661975/58116538-7237b180-7bf4-11e9-95fc-9a763a1466ea.png">

Curious if it's something you've come across before?

**Comment by PTaylour** [comment]
Hi!

I can't reproduce on this example http://bbc.github.io/VideoContext/examples/transitions.html, can you?

And nothing jumps out looking out your code.

Which office are you in? May be easiest if I just pop in and take a look at it in action

**Comment by pietrop** [comment]
Hi Peter, 
I am working from home today, can either do a slack call, or can wait till next week, I am generally in NBH, let me know what works best.

**Comment by PTaylour** [comment]
I'll message on slack
