### ISSUE TITLE
dynamic sequencing and looping

### ISSUE THREAD

**Issue by joemidi** [bbc/VideoContext#18]
Is it possible to dynamically create the timeline and have the last video in the timeline loopable?

**Comment by MatthewShotton** [comment]
Hi Joemidi,

The timeline is completely dynamic, you can add/remove videos at any time (calling "start(n)" on a node starts it after n seconds from the currentTime, calling "startAt(n)" on a node starts it absolute time n on the timeline).
It's also possible to loop VideoNodes infinitely. Something like the following should get you started:

```
var ctx = new VideoContext(document.getElementById("canvas"));
var node1 = ctx.createVideoNode("./video1.mp4");
var node2 = ctx.createVideoNode("./video2.mp4", undefined, undefined, {loop:true})
node1.start(0);
node1.stop(10);
node2.start(10);
```

This will play video1.mp4 from time 0 to time 10, and from time 10 video2.mp4 will play in a loop forever (or until "stop(0)" is called on it).

Hope that helps. Let me know if you have any more questions.

**Comment by joemidi** [comment]
Can I create a `VideoNode` after the `VideoContext` has started playing? Or do all nodes have to be created at the start?

This is kinda what I'm after; http://codepen.io/joemidi/pen/MjNroy

The ability to select loopable sections of video, and cross-fade between those changes.

**Comment by MatthewShotton** [comment]
Hi,
Ah OK, Yeah absolutely, they can be created at any time, and nodes can be disconnected/connected in the processing graph at any time.

This is an interesting use-case for the VideoContext, give me a bit and I'll hack something up on a fork of that codepen to test how it might be approached.

**Comment by MatthewShotton** [comment]
Hi,
Here's a way of acheiving it:
http://codepen.io/anon/pen/dpxKEP

Transition nodes can be a bit tricky to juggle the inputs of. The "transitionTo" function in the above codePen attempts to manage that by checking the mix property of the transition node to figure out which input is active, and handling the disconnecting & resetting of the old connected node, and attaching a new one.

The code in that codepen is a bit rough (there's a few edge cases need ironing out, such as what to do if a transition is cued when a transition is already happening), but hopefully will put you on the right track!

Hope that's helpful.

Kind regards,
Matt

**Comment by joemidi** [comment]
Thanks @MatthewShotton that's wonderful! Really appreciate your help.
