### ISSUE TITLE
Gifs not supported in image nodes

### ISSUE THREAD

**Issue by MatthewShotton** [bbc/VideoContext#19]
ImageNodes fail to correctly render gifs. Only rendering the first frame. As discovered by @jontutcher .

**Comment by gsouquet** [comment]
I'm not sure this is VideoContext's responsibility to decode a GIF and mimic its playback. Now that we can register a custom source node type, it is easier to bring in a library like [Gifler](https://github.com/themadcreator/gifler).

Should we close this issue now?

**Comment by PTaylour** [comment]
yep, thanks @gsouquet
