### ISSUE TITLE
github.io documentation is out of date

### ISSUE THREAD

**Issue by PTaylour** [bbc/VideoContext#20]
The docs at http://bbc.github.io/VideoContext/doc/ are older than the JSDocs in the actual code. 

Can these be updated?

**Comment by MatthewShotton** [comment]
Documentation has been updated and moved from the gh-pages branch to the /docs folder in the root of the project. The ```npm run build``` command now also triggers the documentation to be built so will keep everything up to date in the future.

Kind regards,
Matt
