### ISSUE TITLE
Expose internal nodes for extending

### ISSUE THREAD

**Issue by mmtftr** [bbc/VideoContext#208]
I am working on a project that utilizes VideoContext and we want to extend MediaNode and such but it seems we have to use unorthodox means to get our custom nodes because VideoContext only exports the VideoContext class.

Is it possible for you to also export the classes of VideoNode, MediaNode, SourceNode and so on?

**Comment by germain-gg** [comment]
Hi @MMDF ,

There is the concept of a `CustomSourceNode`. There is a mention of it in the [README.md](https://github.com/bbc/VideoContext#customsourcenode)
I believe this covers most use cases but let me know if you can't achieve what you want here

**Comment by mmtftr** [comment]
Thanks, I did not realize that that was possible.  I was getting the prototypes and extending manually.
