### ISSUE TITLE
registerCallback("ended", function(){console.log("Playback ended");}); is not happen

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#22]
const canvas = document.getElementById('canvas');
 this.ctx = new VideoContext(canvas);
 this.ctx.registerCallback("ended", function(){console.log("Playback ended");});

but when ctx.currentTime == ctx.duration the callback is not happen,there is no console

**Comment by MatthewShotton** [comment]
Hi!

Thanks for finding that.
The bug was caused by an embarrassing typo. It should be fixed in v0.33.1 which has been published to npm now as well.

Kind regards,
Matt
