### ISSUE TITLE
ImageNode  not play after seek

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#23]
var canvasElement = document.getElemenyById("canvas");
this.ctx = new VideoContext(canvasElement);
var imageNode = this.ctx.image("image.png");
this.ctx.startAt(0);
this.ctx.stopAt(15);
imageNode.connect(this.ctx.destination);

btn.click(function(){
  ctx.currentTime = 10;
  ctx.play();
})

After i click btn the ctx is not play; and i saw the ctx.currentTime is still 10s。But change image to video is play ok.

**Comment by MatthewShotton** [comment]
Hi!

Thanks for finding this one. It looks like it was an issue with the image node incorrectly setting it's internal state to "not ready" when it was being seeked into.

A fix for this has been pushed and publushed to npm as v0.33.2.

Kind regards,
Matt
