### ISSUE TITLE
How to position element on the canvas?

### ISSUE THREAD

**Issue by khanzzirfan** [bbc/VideoContext#233]
Hi , if I have to overlap emojis or image on top of video, how to position them based on x y values? is there a method exposed in the videocontext?

**Comment by galipmedia** [comment]
There is a definition for positioning a layer here, no idea how it works though. https://github.com/bbc/VideoContext/tree/develop/src/Definitions such a shame no one is maintaining this code.

**Comment by stephenjolly** [comment]
@galipmedia thanks for helping out with this issue.
