### ISSUE TITLE
frame is not change but ctx.currentTime is add

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#24]
const canvas = document.getElementById('canvas');
this.ctx = new VideoContext(canvas);
const node = this.ctx.video('video.mp4');
node.startAt(0);
node.stopAt(15);
node.connect(this.ctx.destination);

function play () {
this.ctx.play();
}

function pause () {
this.ctx.pause();
}

sometimes first play(); the VideoContext is not change the frame but  ctx.currentTime is adding; then after click pause to start, the frame is change but currentTime is not right. 

1. click play():  ctx.currentTime is adding; frame not change
2. click pause():  ctx.currentTime is 10s,the ctx is pause
3. click play(): ctx.currentTime is adding from 10s, but video is play from 0s, after 5s the ctx is stop(because i set node.stopAt(15))

It just happens sometimes, not every time

**Comment by MatthewShotton** [comment]
Hi,

Thanks for finding another!

I'll have a look at recreating this and working on a fix.
 
We've previously seen issues similar to this depending on the encoding of the video and on how the video is being served. 

For encoding we recommend the video is encoded with a fast decode profile which can be done with avconv/ffmpeg with something like this:
```
avconv -i input.mp4 -tune fastdecode -strict experimental output.mp4
``` 

For best performance when serving the video it should be hosted on server which supports asynchronous connections  (pythons SimpleHTTPServer is not good, but the http-server node.js module works well for testingg). Also the server should support (byte-range requests)[https://en.wikipedia.org/wiki/Byte_serving] for best performance

Your issue might not be related to the above, but if possible it might be worth testing with different video/server combinations to see if the problem persists.

Kind regards,
Matt

**Comment by Statfine** [comment]
Hi, after you fix last bug, i fount this problem is not happen(maybe the times become less) .No matter how thanks very much

**Comment by MatthewShotton** [comment]
Thanks for letting me know, I'll mark this as closed for now.
