### ISSUE TITLE
Negative PlaybackRate

### ISSUE THREAD

**Issue by barata0** [bbc/VideoContext#32]
Negative playbackRate should play the video in reverse mode or it should not be allowed to have negative values.

**Comment by MatthewShotton** [comment]
H @barata0 

Thanks for spotting this! I've pushed v0.34.2 to github and npm which now throws a range error if the playbackRate is ever set <= 0. I've avoided reverse mode for now as from my brief research it looks like that currently isn't supported in base html5 video elements. 

Kind regards,
Matt
