### ISSUE TITLE
CrossFade values are opacity or transparency?

### ISSUE THREAD

**Issue by barata0** [bbc/VideoContext#35]
The transition function is:
transition(startTime, endTime, currentValue, targetValue, propertyName)

currentValue and targetValue define opacity or transparency?

1.0 is 100% opaque or 100% transparent?

It is working like 100% transparency but for a CrossFade transition I think it should indicate the oposite.

Does this make sense to you?

**Comment by MatthewShotton** [comment]
hi @barata0 

The ```currentValue``` and ```targetValue``` define the "mix" between the first and second inputs to transition between. Where 0.0 is 100% first input and 1.0 is 100% second input. (The [fragment shader code for a crossfade](https://github.com/bbc/VideoContext/blob/master/src/Definitions/crossfade.js) will hopefully give you an idea of how this mix property is used, color_a is pixels from the first input, color_b is pixels from the second input, and mix is the parameter being adjusted by the transition node).

The order of inputs is defined by the order in which you connect nodes to the transistion.
``` JavaScript
var video1 = ctx.video("video1.mp4");
var video2 = ctx.video("video2.mp4");
var transition = ctx.transition(VideoContext.DEFINITIONS.CROSSFADE);

video1.connect(transition);
video2.connect(transition);
transition.transition(4,5,0.0,1.0);

transition.connect(ctx.destination);
```

The above code will transition from video1 to video2 between times 4 and 5. But if we swap the order of connections to the transition node:

```
video2.connect(transition);
video1.connect(transition);
``` 

It will break and you'll only see vide between times 4 and 5 and at either side of that will be blank.

I hope that makes things a bit clearer!

Kind regards,
Matt
