### ISSUE TITLE
single videoNode before and after adding transition is not work

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#39]
this.ctx = new VideoContext(canvas)
const node = this.ctx.video('mp4');
node.startAt(0);
node.stopAt(10);

const node2 = this.ctx.video('mp4');
node2.startAt(5);
node2.stopAt(20);

const node3 = this.ctx.video('mp4');
node3.startAt(15);
node3.stopAt(25);

const crossFade = this.ctx.transition(VideoContext.DEFINITIONS.HORIZONTAL_WIPE);
const crossFade2 = this.ctx.transition(VideoContext.DEFINITIONS.CROSSFADE);

node.connect(crossFade);
node2.connect(crossFade);
crossFade.connect(this.ctx.destination);
crossFade.transition(5, 10, 0.0, 1.0);

node3.connect(crossFade2);
crossFade2.connect(this.ctx.destination);
crossFade2.transition(15, 20, 0.0, 1.0);

**Comment by Statfine** [comment]
crossFade.transition(5, 10, 0.0, 1.0) is ok but crossFade2 is not work, and after end do replay node2 is show "nocontent"

**Comment by MatthewShotton** [comment]
@Statfine Hi!,

Your crossFade2 doesn't work because it only has one input connected to it.

The simplest way to fix this is to connect crossFade to the first input of crossFade2 instead of connecting it to the destination:

``` JavaScript
node.connect(crossFade);
node2.connect(crossFade);
crossFade.transition(5, 10, 0.0, 1.0);

crossFade.connect(crossFade2); //connect to input of crossfade2 rather than destination.
node3.connect(crossFade2);

crossFade2.connect(this.ctx.destination);
crossFade2.transition(15, 20, 0.0, 1.0);
```

I will have a look into the bug affecting the replay shortly.

Kind regards,
Matt

**Comment by MatthewShotton** [comment]
Also, this file:
https://github.com/bbc/VideoContext/blob/master/docs/js/utils.js
Has some useful code for creating a visualisation of the videocontext's timeline and graph which can be useful for debugging.
It will create diagrams like on the bottom of this page: http://bbc.github.io/VideoContext/examples/transitions.html

**Comment by MatthewShotton** [comment]
@Statfine 
I've pushed a fix for the "nocontent" being fired when replaying the composition as 0.38.3 to npm and github.

This was due to the underlying video element being set to undefined when a node had finished playing, which caused an error callback to be called on the underlying video element and the video node to be incorrectly tagged as being in an error state.

**Comment by Statfine** [comment]
thanks; it's good for me

**Comment by Statfine** [comment]
@MatthewShotton   
I have another question，at the end of the video to achieve special effects, i can do like this
const node = this.ctx.video('mp4');
node.startAt(0);
node.stopAt(10);
const crossFade = this.ctx.transition(VideoContext.DEFINITIONS.CROSSFADE); // 渐显

node.connect(crossFade);
crossFade.connect(this.ctx.destination);
crossFade.transition(7, 10, 0.0, 1.0);

but if i want at the begin of the video to achieve special effects; what can i do?? l have change crossFade.transition(0, 3, 0.0, 1.0); but it's not well

**Comment by MatthewShotton** [comment]
@Statfine you can swap around the last two parameters like so:
```JavaScript
crossFade.transition(0, 3, 1.0, 0.0); 
```

The last two parameters define what to change the mix parameter from and to. So in this new code the transition is happening from the second input to the first input.

The definition file for the crossfade should give some insight into what is going on (if you look in the "fragmentShader" section "color_a" is the first input and "color_b" as the second input):
https://github.com/bbc/VideoContext/blob/master/src/Definitions/crossfade.js

Hope that makes sense!

**Comment by Statfine** [comment]
so shouldn't used this function if there is only one input?

**Comment by MatthewShotton** [comment]
If there's only one input the other input will default to being transparent, so you can use it with only one input if you like. It depends on what effect you are looking to achieve!

**Comment by Statfine** [comment]
@MatthewShotton   Oh, I see,thank you very much
