### ISSUE TITLE
Audio tracks/audio mixer - planned?

### ISSUE THREAD

**Issue by jesperstarkar** [bbc/VideoContext#50]
Any plans to add support for simple audio mixing/audio follow video or similar?

**Comment by MatthewShotton** [comment]
Hi @jesperstarkar great question. This is something that's come up previously and we don't have a really nice solution to it yet.

You can currently use the WebAudio API with the VideoContext but the integration between the two is a bit awkward. The following is an example of creating a [MediaElementAudioSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource) from a video node:
```JavaScript
var canvas = document.getElementById("canvas");
var ctx = new VideoContext(canvas);
var audioContext = new AudioContext();

var video = ctx.video("./introductions.mp4", 1600);
video.start(0);
video.stop(5);
video.connect(ctx.destination);
video.registerCallback("loaded", ()=>{
    //Wait till the node has loaded so a video element exists.
    var a1 = audioContext.createMediaElementSource(v1.element);
    a1.connect(audioContext.destination);
})

ctx.play();
```

Doing things this way also means you have to create and manage your own cross-fades that follow the transitions of a transition node, which isn't very nice!

I'll have a look at adding in some experimental convenience functions in a future release that hide away some of the complexities.

**Comment by jesperstarkar** [comment]
Thank you so much for the work and this great library.

Since our upcoming project won't have much need to audio mixing, I don't think I'll tap into this issue at the moment. But I hope to find other areas to contribute on.

**Comment by byronmejia** [comment]
@MatthewShotton - Do you have any suggestions with where to start researching? I'll be needing to look into audio soon, so might as well see how to commit back to the project rather than doing in house hacks.

**Comment by PTaylour** [comment]
This is back on our radar now. We'd either like to ease combining videocontext and audiocontext or provide some functionality within the library.

 I'm closing this particular issue for now.
