### ISSUE TITLE
Initial load race condition "cannot set property 'playbackRate' of undefined"

### ISSUE THREAD

**Issue by alex2** [bbc/VideoContext#51]
About 60% of the time when we instantiate multiple videocontext instances at the same time where some have multiple source nodes, we see the following error:
```
Uncaught TypeError: Cannot set property 'playbackRate' of undefined
    at VideoNode._update (videocontext.js:1561)
    at VideoContext._update (videocontext.js:945)
    at UpdateablesManager._update (videocontext.js:3074)
    at UpdateablesManager._updateRAFTime (videocontext.js:3066)
```
which is followed by the videocontext instances failing. Based on the traceback above, there seems to be some situation where a `SourceNode` can have no `this._element` but where the `this._state` is `SOURCENODESTATE.playing`.

We've not seen this issue occur when loading videocontext instances where each has just a single source node.

I've looked to see if I can find any glaring error conditions at our end and can't. We're not sending any options to the videocontext constructor, just the canvas, so it could perhaps have something to do with the videoelementcache.

**Comment by MatthewShotton** [comment]
Hey  @alex2 .

I'm having a go at re-creating this to try and fix it. My current test has 4 video contexts with 3 video nodes each, with all nodes starting at time 0 (so all in 12 video elements being used), and I'm yet to see the error. Is that usage pattern roughly equivalent to yours?

I'm trying to think of differences between my test and your usage, I'm guessing you're passing in MediaStreams to the ```ctx.video()``` call?

It'd be useful to see if:

1. The error callback on any of the video nodes gets thrown ```videoNode.registerCallback("error", ()=>{console.log("error thrown!");}```

2. Disabling the videoelementcache fixes the problem ```const ctx = new VideoContext(canvas, undefined, {useVideoElementCache: false});
