### ISSUE TITLE
Easier set volume

### ISSUE THREAD

**Issue by gossi** [bbc/VideoContext#55]
I could not find the volume for the `VideoContext`. Instead, each source has its own volume. I - and I guess most others as well - treat the whole composition as one video with one volume control. However if I do have build an UI around video context, setting the volume, is cycle through all source nodes and set it on each. I was wondering, whether there is a default volume, that is set on all source nodes, when they are added and when set is applied onto all present source nodes as well.

In pseudo code:

```
VideoContext {
    get volume(); // returns the default volume
    set volume(value); // sets the default volume and applies it to all present source nodes
}
```

Would be wonderful to have that.

**Comment by MatthewShotton** [comment]
Hey Gossi.

This sounds like a good idea! I'll add it in shortly.

**Comment by MatthewShotton** [comment]
This has been added to v0.51.0 available here or on npm.

I'll close this issue for now. Feel free to re-open if you find any bugs!

**Comment by gossi** [comment]
Wow. You are amazing!
