### ISSUE TITLE
Managing z-layer

### ISSUE THREAD

**Issue by gossi** [bbc/VideoContext#57]
The z-layers of my tracks change and I would like to be able to change them programmatically, yet haven't found a way.

As far as I can see, the z-layer is determined at the time a sourcenode is connected to the videocontext. Changing the z-layer later on is impossible? Do I have to kill all sourcenodes first and then add them in the new order again? What about a `sourceNode.layer = value`? (layer was just the best name I could come up with at the moment though I'm pretty sure, you already have some internal value here)

**Comment by MatthewShotton** [comment]
hey @gossi 

One way around this for the time being is to disconnect a SourceNode and reconnect it at a different layer. You can explicitly set the z-layer of a connect when you call connect i.e:

``` JavaScript
const videoNode1 = ctx.video("video1.mp4");
const videoNode2 = ctx.video("video1.mp4");

videoNode1.connect(ctx.destination, 2);
videoNode2.connect(ctx.destination, 1);
```

This will render ```videoNode1``` on top of ```videoNode2``` despite the connection order.

You can also disconnect/reconnect nodes at any time and with very little overhead (you shouldn't see any visual artifacts if you disconnect and then reconnect straight away).
