### ISSUE TITLE
video is black, sound is playing

### ISSUE THREAD

**Issue by gossi** [bbc/VideoContext#62]
I made the switch from desktop to mobile development, using cordova.

Cordova and mobile platforms are kinda weird when it comes to path and URLs for files. Cordova mainly offers two urls: `file://` and `cdvfile://` to access videos on the mobile device. The apps itself are served via `file://android_asset/www/index.html` (as prod build) or via `http://` (dev build). Also there are many restrictions that need to be adjusted to load locally available videos (CORS and mobile device access whitelisting). Using a standard `<video>` element with one of the urls above as `element.src` works quite nice. Setting the `crossorigin` attribute to `anonymous` can make the video unloadable (which is a must to display it onto canvas). I was able to load a video in a prod build (served as `file://`) from `file://` with anonymous crossorigin. At least I could instruct the `VideoContext` to play, however the screen was black, yet the audio gives sound.

From [MDN video element reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video):

> **`crossorigin`** This enumerated attribute indicates whether to use CORS to fetch the related image. CORS-enabled resources can be reused in the <canvas> element without being *tainted*

Since I set CORS to whitelist my video origin, which finally made the `VideoContext` play but only sound, I'm wondering whether you experienced this field before and if you have a good advise to make this library usable on mobile devices (using cordova).

Thanks

**Comment by MatthewShotton** [comment]
Hi @gossi 

Unfortunately I haven't any experience using VideoContext with cordova. But my initial thoughts are that it sounds like it might be a WebGL issue.

I know WebGL has some extra  CORS restrictions (see [here](https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html)) around uploading images to texture memory (which the VideoContext does under the hood) which may be effecting you.

I'll have a bit more of a think and let you know if anything else springs to mind.

**Comment by gossi** [comment]
Thanks matthew, the article helped to explain the background. I was struggling whether I finally configured CORS correctly to made the video play in general (well audio only) or whether I did something else correctly to made the video play. After reading the article I was kinda sure, I did something else correctly and CORS is wrong, because the video is black "*tainted*". Until now, where I was able to get a debug log from AndroidStudio:

```
09-26 14:58:49.353 1225-1225/com.app I/chromium: [INFO:CONSOLE(1)] "VideoContext - playing", source: file:///android_asset/www/assets/vendor-db81a781cd739e2ceb2d03dbdbd144b5.js (1)
09-26 14:58:49.362 1225-1225/com.app W/AudioManager: Use of stream types is deprecated for operations other than volume control
09-26 14:58:49.362 1225-1225/com.app W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-26 14:58:49.370 1225-1309/com.app I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
09-26 14:58:49.374 1225-1309/com.app I/AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 1024 -> 1024
09-26 14:58:49.374 1225-1309/com.app D/AudioTrack: Client defaulted notificationFrames to 512 for frameCount 1024
09-26 14:58:49.395 1225-8070/com.app D/SurfaceUtils: connecting to surface 0x74cdfda010, reason connectToSurface
09-26 14:58:49.395 1225-8070/com.app I/MediaCodec: [OMX.Nvidia.h264.decode] setting surface generation to 1254402
09-26 14:58:49.395 1225-8070/com.app D/SurfaceUtils: disconnecting from surface 0x74cdfda010, reason connectToSurface(reconnect)
09-26 14:58:49.395 1225-8070/com.app D/SurfaceUtils: connecting to surface 0x74cdfda010, reason connectToSurface(reconnect)
09-26 14:58:49.408 1225-8071/com.app D/SurfaceUtils: set up nativeWindow 0x74cdfda010 for 1920x1080, color 0x106, rotation 0, usage 0x2b00
09-26 14:58:49.500 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.503 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.510 1225-8071/com.app D/SurfaceUtils: set up nativeWindow 0x74cdfda010 for 1920x1088, color 0x106, rotation 0, usage 0x2b00
09-26 14:58:49.510 1225-8071/com.app W/ACodec: [OMX.Nvidia.h264.decode] setting nBufferCountActual to 15 failed: -1010
09-26 14:58:49.510 1225-8071/com.app W/ACodec: [OMX.Nvidia.h264.decode] setting nBufferCountActual to 14 failed: -1010
09-26 14:58:49.510 1225-8071/com.app W/ACodec: [OMX.Nvidia.h264.decode] setting nBufferCountActual to 13 failed: -1010
09-26 14:58:49.512 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.513 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.514 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.533 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.583 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.585 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.587 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.593 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.594 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.596 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.597 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:49.604 1225-8071/com.app W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
09-26 14:58:52.950 1225-1233/com.app I/zygote64: Do partial code cache collection, code=124KB, data=86KB
09-26 14:58:52.950 1225-1233/com.app I/zygote64: After code cache collection, code=124KB, data=86KB
09-26 14:58:52.950 1225-1233/com.app I/zygote64: Increasing code cache capacity to 512KB
09-26 14:58:53.264 1225-1225/com.app D/SystemWebChromeClient: file:///android_asset/www/assets/vendor-db81a781cd739e2ceb2d03dbdbd144b5.js: Line 1 : VideoContext - pausing
09-26 14:58:53.264 1225-1225/com.app I/chromium: [INFO:CONSOLE(1)] "VideoContext - pausing", source: file:///android_asset/www/assets/vendor-db81a781cd739e2ceb2d03dbdbd144b5.js (1)
09-26 14:59:03.274 1225-1309/com.app D/AudioTrack: stop() called with 666624 frames delivered
                                                                      
                                                                      [ 09-26 14:59:03.276  1225: 1309 D/         ]
                                                                      PlayerBase::stop() from IPlayer
09-26 14:59:08.289 1225-8066/com.app W/cr_MediaCodecBridge: Releasing: OMX.Nvidia.h264.decode
09-26 14:59:08.321 1225-8070/com.app D/SurfaceUtils: disconnecting from surface 0x74cdfda010, reason disconnectFromSurface
09-26 14:59:08.343 1225-8066/com.app W/cr_MediaCodecBridge: Codec released
```

The debug log is a sequence from pressing play to pressing stop on my video-player-gui which I build around the VideoContext (it was playing just a couple of seconds). The messages about the wrongly allocated buffer plus the  `W/GrallocMapperPassthrough` to a buffer descriptor with invalid bit usage let me rethink, there is something else wrong. Maybe some WebGL interaction on how the video is put onto the canvas? For me this is fishing in the dark (well, literally :D) but when it comes to the video putting on canvas this is your domain and I am wondering whether you can help out here?

Thanks a lot.

**Comment by abhaysofttech** [comment]
I faced similar issue, I resolved it adding `android:hardwareAccelerated="true"` in AndroidManifest.xml in `<application>` tag
