### ISSUE TITLE
Playing a WebM results in the final frame remaining visible until VideoContext is restarted.

### ISSUE THREAD

**Issue by JohnGrayDCLabs** [bbc/VideoContext#65]
Hi,

We have been testing WebM videos with alpha in VideoContext, overlaying on top of another video. It works well except for when the video ends, the final frame is still visible on the canvas until VideoContext is restarted.

We have checked the source node with the WebM video and it definitely looks like it ends correctly and is unloaded by VideoContext.

Is there any other reason we would be seeing this behaviour?

Thanks,

John

**Comment by MatthewShotton** [comment]
Hi @JohnGrayDCLabs 

Thanks for raising this. It's very exciting to learn that WebM supports an alpha channel!

I'm having a bit of trouble re-creating this issue to troubleshoot it, do you have a simplified example you're able to share?

A useful thing to check is that the VideoNode has indeed ended correctly, attaching an "ended" event listener to the VideoNode and checking it's fired should give an indication.

```
var videoNode = ctx.video("clip.mp4");
videoNode.start(0);
videoNode.stop(10);

videoNode.registerCallback("ended", ()=>{
    console.log("video ended!");
});

```

Regards,
Matt

**Comment by JohnGrayDCLabs** [comment]
Hi @MatthewShotton 

Thanks for the response. We will prepare a small reproduction project as soon as possible and get it over to you to see if you can see what is causing the issue.

We have checked the the ended event is occurring (the video node is unloaded after the canvas reports that playback has ended) but will double check in our repro case before sending it on to you.

Cheers,

John
