### ISSUE TITLE
Changing playbackRate unaffects the video rendering

### ISSUE THREAD

**Issue by gossi** [bbc/VideoContext#68]
I do have a very strange situation. I developed a video player around VideoContext, which is great. It runs in electron, which sounds like a pretty stable context for running a webapp. However, video behaves different across systems. I have 4 buttons to change playback rate: 0.5x, 1x, 2x and 5x. It works well for me, yet for some of my colleagues, when they select 5x, the time updates accordingly, yet the frames are still being rendered at 1x speed. It's difficult to narrow this error down to what's responsible for that. What might be cause for VideoContext to still render the frames at 1x speed while actually it is 5x ?

Thanks a lot

**Comment by PTaylour** [comment]
That's interesting. So the `videoContext.currentTime` is updating 5x faster than what is rendered?

Does `currentTime` of the rendered videoElement(s) keep in sync with the `videoContext.current` time, or does that remain at 1x?

**Comment by gossi** [comment]
Good question, I don't know. What I'm wondering more about is the code is the equal across my installation and the one of my colleagues, though different behaviors.

I think, I will make a debug build to check these whether there are differences between videoContext and videoElement

**Comment by PTaylour** [comment]
feel free to reopen if this is still an issue
