### ISSUE TITLE
Pixelated video and images

### ISSUE THREAD

**Issue by pd-andy** [bbc/VideoContext#74]
So I'm working on a live coding language to wrap around VideoContext; the language is going well but playback is off. Videos and images are extremely pixellated. It may be a problem with my implementation but Ian mentioned having the problem internally at the BBC before, any ideas? I've attached an example below.

<img width="1440" alt="vid-example-bad" src="https://user-images.githubusercontent.com/9001354/37234003-6d480b76-23ed-11e8-9254-e56866bd09bd.png">
<img width="1530" alt="vid-example-good" src="https://user-images.githubusercontent.com/9001354/37234004-6d643d1e-23ed-11e8-8104-3fccb3b0d0de.png">

**Comment by PTaylour** [comment]
Sounds exciting!

Have you set the canvas width and height attributes?

If you haven't, the canvas will use its defaults, which results in a bitmap that's only 300x150 pixels https://html.spec.whatwg.org/multipage/canvas.html#attr-canvas-width

Any css sizing then scales this bitmap, which is probably why your output is pixilated.

To fix, you should set the canvas size attributes to your required resolution.

Does this help?

**Comment by pd-andy** [comment]
Damn how did I miss that, yeah that was exactly it!

It's always the little things eh...

**Comment by PTaylour** [comment]
It's a common issue, at the very least I'll add it to the README examples!
