### ISSUE TITLE
Can save the result as video file???

### ISSUE THREAD

**Issue by KaneYoon** [bbc/VideoContext#76]
if  it can ,Could you give me some clues..

**Comment by PTaylour** [comment]
videocontext renders video using the HTMLCanvas element, but it doesn't provide a way to capture the output.

However, there are libraries out there intended for capturing the output of canvas elements.

I haven't tried it, but https://github.com/spite/ccapture.js/ looks like it could.

**Comment by PTaylour** [comment]
@KaneYoon any luck with capturing the canvas? I'll close this issue if no longer active :)

**Comment by MysteryPancake** [comment]
This can be done via the MediaStream interface:
https://github.com/bbc/VideoContext/issues/156
