### ISSUE TITLE
Original duration of video

### ISSUE THREAD

**Issue by ZulfadhliM** [bbc/VideoContext#77]
Is there a way to get the original length of the video instead of "Infinity"? Lets say the length of the video is 10 seconds. Code example as below:
```
var canvas = document.getElementById("canvas");
var videoCtx = new VideoContext(canvas);
var videoNode = videoCtx.video('./movie.mp4');
videoNode.connect(videoCtx.destination);
videoNode.start(0);
videoCtx.play();
console.log(videoNode.duration); // outputs: Infinity
console.log(videoNode); // outputs: duration: 10
```

**Comment by PTaylour** [comment]
Looking at the code:

The `duration` getter calculates duration from the internal `_stopTime`. Until `_stopTime` is known it returns `Infinity`.

`_stopTime` is set on loading the videoNode if the element has `readyState > 3` (which is `HAVE_ENOUGH_DATA`)

https://github.com/bbc/VideoContext/blob/cc83357fc5ee62d30b97c5ce3eade829a46daf68/src/SourceNodes/videonode.js#L73

So,`videoNode.duration`, as things stand, will only give you the duration once the node has loaded. 

When you do `console.log(videoNode); // outputs: duration: 10`, are you reading the duration from the underlying element?

If you read videoNode.duration on the next tick (eg after requestAnimationFrame), does it still give you `Infinity`?

**Comment by ZulfadhliM** [comment]
Thanks! I used `setInterval()` to fetch the duration until it is ready.
