### ISSUE TITLE
webm videos with alpha transparency flickering

### ISSUE THREAD

**Issue by Sacharified** [bbc/VideoContext#78]
When playing back .webm files with alpha transparency, the video flickers, rapidly appearing and disappearing constantly.
You can reproduce with the code below in the [Video Context code playground](http://bbc.github.io/VideoContext/examples/codeplayground/index.html) and the following webm files from Google Chrome':

- https://simpl.info/videoalpha/video/soccer1.webm
- https://simpl.info/videoalpha/video/dancer1.webm

These files appear to play back normally with alpha transparency in a video element.

webm files with no alpha transparency, such as [this one](https://upload.wikimedia.org/wikipedia/commons/transcoded/2/22/Volcano_Lava_Sample.webm/Volcano_Lava_Sample.webm.480p.webm), appear to play back normally.

```
var canvas = document.getElementById("canvas");
window.vc = new VideoContext(canvas);

var videoNode1 = vc.video("https://simpl.info/videoalpha/video/soccer1.webm", 0);

videoNode1.connect(vc.destination);

videoNode1.start(0);
videoNode1.stop(50);

vc.play();
```

**Browsers:**
Can reproduce in Chrome(only tested v66.0.3359.139)
Cannot reproduce in Firefox(only tested v59.0.2) -  The video plays back normally.
VideoContext does not seem to work at all in Safari
Have not tested Edge

**Comment by PTaylour** [comment]
Hi Sacha, I just tried on chrome 65 and haven't managed to reproduce. Are you getting any errors / logs in 66?

**Comment by Sacharified** [comment]
Hi Pete, no there are no errors or logs. It also works correctly in the latest Chrome Canary (68.0.3427.0), so this issue may be specific to version 66.

**Comment by PTaylour** [comment]
Hi @Sacharified, do you see this issue in chrome 67?

**Comment by Sacharified** [comment]
@PTaylour Yes I still see the same issue in Chrome 67. I don't see the issue on 68 Beta or 69 in Canary.

**Comment by Sacharified** [comment]
I've tested this again and still see the same issue consistently in Chrome 68 and 69.

**Comment by PTaylour** [comment]
I'm still unable to reproduce. Just tried version 69.0.3497.81

👇chrome performance profiler with network and CPU throttling.

[webm-profile-soccer.json.zip](https://github.com/bbc/VideoContext/files/2380992/webm-profile-soccer.json.zip)

We're both testing on Mac, using the playground and same code snippet 🤔

Have you reproduced on multiple machines / with a clean chrome profile?

**Comment by Sacharified** [comment]
@PTaylour I'm no longer seeing this issue on Chrome 72 or 73. There were some Chromium changes which caused issues with WebGL on MBPs with specific GPU versions recently, so it may be that case that we saw different results due to differences in the GPUs between our machines and the bug only affected a limited set of OpenGL GPU renderers.

I'm marking this as closed.
