### ISSUE TITLE
VideoContext module cannot be resolved after updating to 0.52.0 on npm.

### ISSUE THREAD

**Issue by JohnGrayDCLabs** [bbc/VideoContext#91]
Hi guys,

After we updated from 0.51.7 to 0.52.0 on npm, our application no longer resolves the videocontext module.

The following error is produced by webpack:

Module not found: Error: Can't resolve 'videocontext'

Is there anything which has changed which might be causing this behaviour that you can think of? Downgrading back to 0.51.7 results in a successful build again so it definitely seems to be a change from 0.52.0.

Cheers,

John

**Comment by JohnGrayDCLabs** [comment]
Version 0.52.0 onwards does not come with the dist folder so you must build the module yourself.

Once this was done the issue was resolved.

**Comment by Sacharified** [comment]
This is a bit of a strange change, does this mean that we have to go and manually run the build every time we `npm install`? How will that work in a CI pipeline?

**Comment by JohnGrayDCLabs** [comment]
The built version must be included otherwise it is going to be a nightmare as it means everyone on a team knowing that when they download the project, they must manually build VideoContext before trying to build the application which is using it.

**Comment by PTaylour** [comment]
Ah yes, this is CI gone wrong it absolutely should include the built version!

Looking into it now. Apologies for the inconvenience.

**Comment by PTaylour** [comment]
travis file was missing `skip_cleanup: true`

It shouldn't have published the release as it's not on master, but that was another issue that has already been fixed.

**Comment by PTaylour** [comment]
v0.52.4 is live and (thankfully) includes the dist directory.

https://www.npmjs.com/package/videocontext/v/0.52.4

Let me know if you have any other issues. The switch to travis CI is now in master.

Thank you for your patience—it shouldn't have taken this long to fix :)

**Comment by kingpalethe** [comment]
I had this problem also, for me it was solved with

yarn add videocontext@0.52.9

which locks the package to the previous 0.52.9 version. Not sure why this fixed it.

**Comment by PTaylour** [comment]
@kingpalethe which version were you upgrading to when you had this problem? `0.52.10`?

**Comment by PTaylour** [comment]
We switched to the `browser` field in the package.json in `0.52.10`. Perhaps you're using a build system the expects `main` to be defined?

**Comment by Sacharified** [comment]
@PTaylour I had this issue when upgrading to `0.52.10`. Adding the `main` key back to the `package.json` fixed it. What was the reason for the original change?

**Comment by PTaylour** [comment]
Discussed here https://github.com/bbc/VideoContext/pull/110

Shall revert now as causing you guys problems
